### ISSUE TITLE
remodifier le logo "mon site"

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#19]
remodifier le logo "mon site" (je te lai mis dans les medias)

**Comment by leslieharicots** [comment]
j'aime pas le logo mon site mais c moi je trouve que ca marche pas, tu en penses quoi ?

**Comment by marioncointre** [comment]
Je suis d'accord.

Je pense qu'il vaudrait mieux le mettre par dessus et qu'il suive le scroll come sur ciel:

https://www.ciel.com/
