### ISSUE TITLE
mettre en vert si tu penses que c bien 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#25]
mettre en vert ces trois categories qui a la base sont noirs, si tu penses quen vert ca peut etre cool 
<img width="258" alt="capture d ecran 2018-10-24 a 20 15 42" src="https://user-images.githubusercontent.com/44237867/47452136-bdf2bb80-d7c9-11e8-85f7-c8a5b7368106.png">

**Comment by marioncointre** [comment]
c'est fait
