### ISSUE TITLE
can you make it in french :) 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#27]
<img width="385" alt="capture d ecran 2018-10-25 a 15 27 35" src="https://user-images.githubusercontent.com/44237867/47503766-32316b80-d86b-11e8-91c2-adbfd52f9ea0.png">
<img width="192" alt="capture d ecran 2018-10-25 a 15 27 40" src="https://user-images.githubusercontent.com/44237867/47503768-32316b80-d86b-11e8-932e-14832afea5de.png">

**Comment by marioncointre** [comment]
pour l'instant je ne trouve pas le browsing
