### ISSUE TITLE
est ce que cela peut etre mis sur deux colonnes ? 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#28]
est ce que cela peut etre mis sur deux colonnes ? 
je me dis qu;au fur et a mesure ca peut etre long mais encore une fois je sais pas si c possible 
<img width="325" alt="capture d ecran 2018-10-25 a 15 27 43" src="https://user-images.githubusercontent.com/44237867/47503848-55f4b180-d86b-11e8-925d-51ffe19365b6.png">

**Comment by marioncointre** [comment]
Tu penses faire plus de catégories?

Sinon là je te lai mis en liste déroulante
