### ISSUE TITLE
est ce que tu penses pouvoir telecharger le fond et essayer de voir si ca marche ? 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#31]
est ce que tu penses pouvoir telecharger le fond et essayer de voir si ca marche ? 
tu peux me l'envoyer et je te le mettrais a la taille souhaite et en vectoriel si tu veux

**Comment by marioncointre** [comment]
Pour l'intant c'est pas concluant car c'est soit dans le header soit dans le body

**Comment by marioncointre** [comment]
![capture d ecran 2018-10-26 a 16 12 00](https://user-images.githubusercontent.com/33253283/47571902-f74a3900-d939-11e8-85f5-1c734cf98a72.png)
![capture d ecran 2018-10-26 a 16 12 06](https://user-images.githubusercontent.com/33253283/47571914-fd401a00-d939-11e8-81da-f5e9200ffcb4.png)

**Comment by leslieharicots** [comment]
ah oui merde en effet, faudrait quil soit plus petit c clair mais ca doit pas etre facile 
veux tu que je te redimensionne l'image ou ca change rien ?

**Comment by marioncointre** [comment]
Je peux jouer sur la transparence mais j'ai un gros doute sur le rendu quand même

**Comment by leslieharicots** [comment]
coucou tu peux essayer et si ca marche pas et bien on ne fait pas cest pas grave tkt pas ;)

**Comment by marioncointre** [comment]
![capture d ecran 2018-10-29 a 13 47 26](https://user-images.githubusercontent.com/33253283/47650664-3b7b4a80-db81-11e8-83b8-c58d33efc471.png)
