### ISSUE TITLE
mettre N majuscule a normandie stp 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#32]
<img width="157" alt="capture d ecran 2018-10-25 a 15 56 10" src="https://user-images.githubusercontent.com/44237867/47505508-90ac1900-d86e-11e8-8706-5147cccf602e.png">

**Comment by marioncointre** [comment]
à normande tu veux dire?

**Comment by leslieharicots** [comment]
Oui tout à fait 

> Leslie Chemouny
> Graphiste / D.A 
> Www.lesliechemouny.com
> 
> Book /  https://goo.gl/tCSoXY
> Tel / + 33 (0)6 65 59 65 34
> 
>
