### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#36]
j'ai cree mon truc google analytics mais apres j;ai un peu galere pour savoir ou coller mon code 
http://creer-un-site.com/obtenir-statistiques-visites-site/

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-128238877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-128238877-1');
</script>

**Comment by marioncointre** [comment]
Peux tu me rajouter à ton google analytics? marion.cointre@gmail.com

**Comment by leslieharicots** [comment]
je sais pas comment on fait, j'ai cherche et je trouve pas. je me connecte automatiquement grace a mon gmail mais rajouter un mail je sais pas :(
