### ISSUE TITLE
a propos dans la barre a droite

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#4]
j'ai mis ma bio ultra qualitative :) il faudrait que je prenne une photo un peu potable

**Comment by marioncointre** [comment]
Il me man

**Comment by leslieharicots** [comment]
es til possible de mieux definir les choses dans la bio ?
mettre en gras "food-....'
mettre le parisienne a la ligne ?
(je suis pire au'illicado) 
<img width="323" alt="capture d ecran 2018-10-17 a 19 01 07" src="https://user-images.githubusercontent.com/44237867/47103289-39d78b80-d23f-11e8-9ea7-9249d929c7bd.png">

**Comment by leslieharicots** [comment]
il manque ca marion :) 

es til possible de mieux definir les choses dans la bio ?
mettre en gras "food-....'
mettre le parisienne a la ligne ?
(je suis pire au'illicado)
