### ISSUE TITLE
changer deux titre 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#40]
a la place de lectures mettre loisirs 
et a la place de maison mettre instants de vie

j;ai pas reussi a le faire la, et je pense que ca va impacter pas mal de choses que je ne sais pas faire

**Comment by leslieharicots** [comment]
<img width="1154" alt="capture d ecran 2018-10-29 a 21 17 05" src="https://user-images.githubusercontent.com/44237867/47677840-86688280-dbc0-11e8-997a-efe93cbce724.png">

**Comment by marioncointre** [comment]
cest fait
