### ISSUE TITLE
marion tu vas me tuer 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#41]
je suis trop dsl mais enfaite je trouve le menu recettes pas clairs du tt mais c ma faute 
 je voudrais ca enfaite 
<img width="225" alt="capture d ecran 2018-10-29 a 21 33 52" src="https://user-images.githubusercontent.com/44237867/47678575-70f45800-dbc2-11e8-8253-b764a4398709.png">

**Comment by leslieharicots** [comment]
Dis moi ce qui ne vas pas Marion attends j’ai besoin de ton avis 

> Leslie Chemouny
> Graphiste / D.A 
> Www.lesliechemouny.com
> 
> Book /  https://goo.gl/tCSoXY
> Tel / + 33 (0)6 65 59 65 34
> 
>

**Comment by marioncointre** [comment]
Non mais en fait vegan et vege je le mettrais pas dans salé car ca peut être dans tout? Et puis de toute facon toutes tes recettes vont être vegan non? 
Et les basiques je ne suis pas sûre de comprendre?

**Comment by leslieharicots** [comment]
Mes recettes sont pas toutes vegan parfois il y aura un peu de fromage ou des œufs c’est ça qui m’embête. Concernant les basiques c’est genre les pâtes sables à la fois sucré ou sales par exemple. 
Enfaite c’est hyper dur ça je trouve de définir un menu pour les recettes comme tout n’est pas vegan 

> Leslie Chemouny
> Graphiste / D.A 
> Www.lesliechemouny.com
> 
> Book /  https://goo.gl/tCSoXY
> Tel / + 33 (0)6 65 59 65 34
> 
>
