### ISSUE TITLE
avoir un histogramme lors d;une recette

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#43]
un truc comme ca 
<img width="747" alt="capture d ecran 2018-10-31 a 14 18 16" src="https://user-images.githubusercontent.com/44237867/47790619-f0e00680-dd17-11e8-9851-773d4d315bd2.png">

**Comment by marioncointre** [comment]
tu veux dire un fil d'ariane?

**Comment by leslieharicots** [comment]
oui je pense que ca s'appelle comme ca

**Comment by marioncointre** [comment]
comme ça?

![capture d ecran 2018-11-02 a 14 19 08](https://user-images.githubusercontent.com/33253283/47917602-4cda9480-deaa-11e8-9799-d2d4db8c8fc9.png)
