### ISSUE TITLE
je n'arrive plus a lier mes recettes a leur menu (urgent) 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#44]
par exemple la coeur coulant je veux quil soit dans recette/sucre/low sugar et dessert (dans les deux)
pareil pour les boissons chaudes (lait vegetal epice, le lait d'or et le pumpkin spicce latte) je voudrais quils soient dans recettes/boissons/boissonschaudes 

mais je n'y arrive plus 
ce que jaime bien cest aussi le fait de clicquer juste sur boissons par exemple et d'avoir ttes les boissons 

pareil pour le sucre, tu cliques sur sucre et tu as tt les dessert... mais je veux egalement quils soit compartimentes

**Comment by marioncointre** [comment]
je ne suis pas sûre de te suivre ici? Car que je clique sur "recette" ou "sucre" ou "low sugar" je retrouve bien le coulant dans toutes les catégories?

**Comment by leslieharicots** [comment]
je crois que j'ai reussi a corriger ca :) merci
