### ISSUE TITLE
je me perds ici est ce possible de faire le tri ? 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#45]
<img width="276" alt="capture d ecran 2018-10-31 a 17 31 49" src="https://user-images.githubusercontent.com/44237867/47803512-f9920600-dd32-11e8-8da8-51b1b04f9b9c.png">

**Comment by marioncointre** [comment]
C'est à dire? Quel tri?

**Comment by leslieharicots** [comment]
comme jai change le menu plusieurs fois, il reste genre "aperitifs" "biscuits"... qui n'existent plus dans le menu actuel

**Comment by marioncointre** [comment]
ok cest retiré
