### ISSUE TITLE
remplacer "superfood" par 'food life" 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#53]
<img width="867" alt="capture d ecran 2018-11-11 a 18 41 13" src="https://user-images.githubusercontent.com/44237867/48316265-9da46880-e5e1-11e8-84c4-67bc9860613a.png">

**Comment by marioncointre** [comment]
Attention : 

<img width="1199" alt="capture d ecran 2018-11-13 a 15 21 41" src="https://user-images.githubusercontent.com/33253283/48419291-d8301180-e757-11e8-9a77-63eb591f2e8c.png">


Tu es sûre?

**Comment by leslieharicots** [comment]
oh mince j'avais pas vu tom message, dans ce cas on garde "superfood"mais on rajouter "mieux consommer" dans soit lifestyle soit recettes tu en penses quoi ?

**Comment by marioncointre** [comment]
Oui mais je le verrai plutôt dans lifestyle non?

**Comment by leslieharicots** [comment]
dans lifestyle c tres bien merci
