### ISSUE TITLE
faire le tri ici stp 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#55]
<img width="403" alt="capture d ecran 2018-11-19 a 14 13 20" src="https://user-images.githubusercontent.com/44237867/48709283-4fa4eb80-ec05-11e8-9ac6-93f8cb948b4d.png">

**Comment by marioncointre** [comment]
C'est à dire "faire le tri"?

**Comment by leslieharicots** [comment]
ah non je viens de comprendre mais c perturbant qu'il y est deux fois "food" par exemple mais j'ai compris pk :)
