### ISSUE TITLE
vegan 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#61]
par exmple ici marion jaimerais mettre une etiquette "vegan" mais je ne veux pas que ca renvoie un mon menu vegan (je n'ai vegan que pour le sale mais pas pour le sucre) donc je veux pas que ma recette sucre se retrouve dans les recettes sales :) 
<img width="370" alt="capture d ecran 2018-11-19 a 14 28 08" src="https://user-images.githubusercontent.com/44237867/48710042-84b23d80-ec07-11e8-99f2-784818f69df3.png">

**Comment by marioncointre** [comment]
En fait tu l'as grâce à ton étiquette "vegan"
http://larevanchedesharicots.com/index.php/tag/vegan/
