### ISSUE TITLE
fond du site 

### ISSUE THREAD

**Issue by leslieharicots** [marioncointre/larevanchedesharicots#8]
enfaite celui ci est mieux 
666902131
<img width="743" alt="capture d ecran 2018-10-17 a 18 02 06" src="https://user-images.githubusercontent.com/44237867/47100045-dea19b00-d236-11e8-8e1c-5ccbc8267513.png">

**Comment by leslieharicots** [comment]
tu prends sur celui de lagence ?

**Comment by marioncointre** [comment]
jai pas les logins de l'agence -> alex les a?

**Comment by leslieharicots** [comment]
oui tout a fait alex les as, ce sont les id de daniel (mais ca se connecte automatiquement) mais alex a bien sur
